##[>] 🤖🤖
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - validate
  - plan
  - apply

variables:
  TF_IN_AUTOMATION: "true"
  GITLAB_TOKEN: $TF_GITLAB_TOKEN
  GOOGLE_CREDENTIALS: $GCP_SA_KEY

default:
  image:
    name: hashicorp/terraform:1.15.7
    entrypoint: [""]
  before_script:
    - apk add --no-cache make zsh

validate:
  stage: validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - make validate

plan:
  stage: plan
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - make plan
  artifacts:
    paths:
      - tf/plan.tfplan
    expire_in: 7 days

apply:
  stage: apply
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - make plan
    - make apply
##[<] 🤖🤖
